apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iiif-dl-tlu-ee-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-rps: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: iiif.dl.tlu.ee
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iiif-dl-tlu-ee-service
            port:
              number: 80
